### ISSUE TITLE
Trouble installing on Windows 8 with NVM and latest node

### ISSUE THREAD

**Issue by sgutkin** [slushjs/slush#22]
I've used NPM to install other packages.  Occasionally I get warnings but this is the first package I cannot install.  It did install fine on Node version 0.10.32.

---
## results from command prompt

c:\mean\dev\x>npm install -g slush
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "-g" "slush"
npm ERR! node v0.11.14-nightly-20140819-pre
npm ERR! npm  v2.0.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: slush@'*'
npm ERR! notarget No valid targets found.
npm ERR! notarget Perhaps not compatible with your version of node?
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\mean\dev\x\npm-debug.log

c:\mean\dev\x>

---
## Contents of the npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'slush' ]
2 info using npm@2.0.0
3 info using node@v0.11.14-nightly-20140819-pre
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose cache add [ 'slush', null ]
6 verbose cache add spec="slush" args=["slush",null]
7 verbose parsed spec { raw: 'slush',
7 verbose parsed spec   scope: null,
7 verbose parsed spec   name: 'slush',
7 verbose parsed spec   rawSpec: '',
7 verbose parsed spec   spec: '_',
7 verbose parsed spec   type: 'range' }
8 verbose parsed spec { raw: 'slush',
8 verbose parsed spec   scope: null,
8 verbose parsed spec   name: 'slush',
8 verbose parsed spec   rawSpec: '',
8 verbose parsed spec   spec: '_',
8 verbose parsed spec   type: 'range' }
9 verbose addNamed [ 'slush', '_' ]
10 verbose addNamed [ null, '_' ]
11 silly lockFile f9dafbae-slush slush@*
12 verbose lock slush@\* C:\Users\sgutkin\AppData\Roaming\npm-cache\f9dafbae-slush.lock
13 silly addNameRange { name: 'slush', range: '_', hasData: false }
14 verbose mapToRegistry name slush
15 verbose mapToRegistry uri https://registry.npmjs.org/slush
16 verbose request on initialization, where is /slush
17 verbose request after pass 1, where is /slush
18 verbose request url raw /slush
19 verbose request resolving registry [ 'https://registry.npmjs.org/', './slush' ]
20 verbose request after pass 2, where is https://registry.npmjs.org/slush
21 verbose request no auth needed
22 info attempt registry request try #1 at 15:04:28
23 verbose request id 2998081f39468a15
24 verbose etag "16SAT270EWAZTFBJ55IPQA7IG"
25 http request GET https://registry.npmjs.org/slush
26 http 304 https://registry.npmjs.org/slush
27 silly registry.get cb [ 304,
27 silly registry.get   { date: 'Wed, 29 Oct 2014 22:04:25 GMT',
27 silly registry.get     server: 'Apache',
27 silly registry.get     via: '1.1 varnish',
27 silly registry.get     'last-modified': 'Wed, 29 Oct 2014 22:04:25 GMT',
27 silly registry.get     'cache-control': 'max-age=60',
27 silly registry.get     etag: '"16SAT270EWAZTFBJ55IPQA7IG"',
27 silly registry.get     age: '0',
27 silly registry.get     'x-served-by': 'cache-lax1435-LAX',
27 silly registry.get     'x-cache': 'HIT',
27 silly registry.get     'x-cache-hits': '1',
27 silly registry.get     'x-timer': 'S1414620265.853916,VS0,VE40',
27 silly registry.get     vary: 'Accept',
27 silly registry.get     'content-length': '0',
27 silly registry.get     connection: 'close' } ]
28 verbose etag https://registry.npmjs.org/slush from cache
29 silly addNameRange number 2 { name: 'slush', range: '_', hasData: true }
30 silly addNameRange versions [ 'slush', [] ]
31 silly lockFile f9dafbae-slush slush@*
32 silly lockFile f9dafbae-slush slush@*
33 verbose stack Error: No compatible version found: slush@'_'
33 verbose stack No valid targets found.
33 verbose stack Perhaps not compatible with your version of node?
33 verbose stack     at installTargetsError (C:\Users\sgutkin\AppData\Roaming\nvm\v0.11.14\node_modules\npm\lib\cache\add-named.js:258:12)
33 verbose stack     at next (C:\Users\sgutkin\AppData\Roaming\nvm\v0.11.14\node_modules\npm\lib\cache\add-named.js:237:17)
33 verbose stack     at setData (C:\Users\sgutkin\AppData\Roaming\nvm\v0.11.14\node_modules\npm\lib\cache\add-named.js:214:5)
33 verbose stack     at saved (C:\Users\sgutkin\AppData\Roaming\nvm\v0.11.14\node_modules\npm\node_modules\npm-registry-client\lib\get.js:167:7)
33 verbose stack     at Object.oncomplete (fs.js:93:15)
34 verbose cwd c:\mean\dev\x
35 error Windows_NT 6.2.9200
36 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "slush"
37 error node v0.11.14-nightly-20140819-pre
38 error npm  v2.0.0
39 error code ETARGET
40 error notarget No compatible version found: slush@'_'
40 error notarget No valid targets found.
40 error notarget Perhaps not compatible with your version of node?
40 error notarget This is most likely not a problem with npm itself.
40 error notarget In most cases you or one of your dependencies are requesting
40 error notarget a package version that doesn't exist.
41 verbose exit [ 1, true ]

**Comment by mjmoody383** [comment]
+1
