### ISSUE TITLE
Cannot initialise slush generator

### ISSUE THREAD

**Issue by graforlock** [slushjs/slush#36]
After typing up slush and generator name in the terminal, it gives me: 

$ slush wordpress
/usr/local/lib/node_modules/slush-wordpress/slushfile.js:20
    var username = string.toLowerCase();
                         ^
TypeError: Cannot read property 'toLowerCase' of undefined
    at format (/usr/local/lib/node_modules/slush-wordpress/slushfile.js:20:26)
    at /usr/local/lib/node_modules/slush-wordpress/slushfile.js:35:19
    at Object.<anonymous> (/usr/local/lib/node_modules/slush-wordpress/slushfile.js:38:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/slush/bin/slush.js:90:3)

**Comment by greenify** [comment]
That is an error in slush-wordpress, please report there https://github.com/acauamontiel/slush-wordpress

**Comment by graforlock** [comment]
It does that with any other generator

**Comment by joakimbeng** [comment]
Closing this then
